// Keeps every part's A/B terrain tables in step with the store.
//
// Whenever terrainA/terrainB/seed/detail/userTerrain of a part changes (or the
// whole state loads) the part is refreshed after a short debounce: each slot's
// wanted table is described as a job (terrain-jobs.js), looked up in an LRU
// cache, otherwise generated by the generator (workers when possible). A
// finished table is posted to the DSP as a mip chain (copies are transferred,
// so the cached arrays stay valid) and announced with an engine 'terrain'
// event carrying the full-resolution level.
//
// Main-thread work per applied table is one copy of the chain (~1.4 MB for
// 512 x 512) plus the post; stats().maxApplyMs records the worst case.

import { NUM_PARTS } from '../core/params.js';
import { jobFor, jobKey } from './terrain-jobs.js';

const SLOT_NAMES = ['A', 'B'];
const REGEN_KEYS = new Set(['terrainA', 'terrainB', 'seed', 'detail']);

function slotIndex(slot) {
  if (slot === 0 || slot === 'A' || slot === 'a') return 0;
  if (slot === 1 || slot === 'B' || slot === 'b') return 1;
  return -1;
}

const now = () => (typeof performance !== 'undefined' ? performance.now() : Date.now());

/**
 * @param {object} o
 * @param {object} o.store the app store
 * @param {(msg: object, transfer: ArrayBuffer[]) => void} o.post sends to the DSP
 * @param {(name: string, payload: object) => void} o.emit engine event emitter
 * @param {{size: number, free(): number, run(job): Promise<Array>}} o.generator
 * @param {number} [o.debounceMs]
 * @param {number} [o.cacheSize] maximum number of cached tables (LRU)
 */
export function createTerrainManager({ store, post, emit, generator, debounceMs = 60, cacheSize = 24 }) {
  const slots = Array.from({ length: NUM_PARTS }, () => [0, 1].map(() => ({ want: null, have: null, failed: null, levels: null })));
  const cache = new Map();
  const queue = new Map();      // key -> job, waiting for a free generator
  const running = new Set();    // keys being generated
  const timers = new Array(NUM_PARTS).fill(0);
  let waiters = [];
  let disposed = false;
  const st = { generated: 0, cacheHits: 0, applied: 0, evicted: 0, errors: 0, maxApplyMs: 0, posted: 0 };

  function cacheGet(key) {
    const v = cache.get(key);
    if (v) { cache.delete(key); cache.set(key, v); }
    return v;
  }

  function cacheSet(key, levels) {
    cache.delete(key);
    cache.set(key, levels);
    while (cache.size > cacheSize) {
      cache.delete(cache.keys().next().value);
      st.evicted++;
    }
  }

  function wantedJob(part, s) {
    const slot = SLOT_NAMES[s];
    const params = store.get(`parts.${part}.params`);
    const ut = store.get(`parts.${part}.userTerrain.${slot}`);
    return jobFor(params, ut || null, slot, generator.size);
  }

  function isWanted(key) {
    for (const part of slots) for (const sl of part) if (sl.want === key && sl.have !== key) return true;
    return false;
  }

  function sendLevels(part, s, levels) {
    const copies = levels.map(l => ({ size: l.size, data: l.data.slice() }));
    post({ t: 'terrain', part, slot: s, levels: copies }, copies.map(c => c.data.buffer));
    st.posted++;
  }

  function apply(part, s, key, levels) {
    const t0 = now();
    sendLevels(part, s, levels);
    const sl = slots[part][s];
    sl.have = key;
    sl.failed = null;
    sl.levels = levels;
    st.applied++;
    st.maxApplyMs = Math.max(st.maxApplyMs, now() - t0);
    emit('terrain', { part, slot: SLOT_NAMES[s], size: levels[0].size, data: levels[0].data });
  }

  function refresh(part) {
    if (disposed) return;
    timers[part] = 0;
    for (let s = 0; s < 2; s++) {
      const job = wantedJob(part, s);
      const key = jobKey(job);
      const sl = slots[part][s];
      sl.want = key;
      if (sl.have === key) continue;
      const hit = cacheGet(key);
      if (hit) { st.cacheHits++; apply(part, s, key, hit); continue; }
      if (!running.has(key) && !queue.has(key)) queue.set(key, job);
    }
    pump();
    settle();
  }

  function pump() {
    while (!disposed && queue.size && generator.free() > 0) {
      const [key, job] = queue.entries().next().value;
      queue.delete(key);
      if (!isWanted(key)) continue;
      running.add(key);
      generator.run(job).then((levels) => {
        running.delete(key);
        if (disposed) return;
        st.generated++;
        cacheSet(key, levels);
        for (let p = 0; p < NUM_PARTS; p++) {
          for (let s = 0; s < 2; s++) {
            const sl = slots[p][s];
            if (sl.want === key && sl.have !== key) apply(p, s, key, levels);
          }
        }
      }, (err) => {
        running.delete(key);
        if (disposed) return;
        st.errors++;
        console.warn('[audio] terrain generation failed', err);
        for (const part of slots) for (const sl of part) if (sl.want === key) sl.failed = key;
      }).finally(() => { pump(); settle(); });
    }
  }

  function idle() {
    if (timers.some(Boolean) || queue.size || running.size) return false;
    for (const part of slots) for (const sl of part) if (sl.want !== sl.have && sl.want !== sl.failed) return false;
    return true;
  }

  function settle() {
    if (!waiters.length || !idle()) return;
    const w = waiters; waiters = [];
    for (const fn of w) fn();
  }

  function schedule(part) {
    if (disposed) return;
    clearTimeout(timers[part]);
    timers[part] = setTimeout(() => refresh(part), debounceMs);
  }

  function partsByPriority() {
    const sel = Math.round(store.get('ui.selectedPart') || 0);
    const order = [];
    for (let i = 0; i < NUM_PARTS; i++) order.push((sel + i) % NUM_PARTS);
    return order;
  }

  const offFree = typeof generator.onFree === 'function' ? generator.onFree(() => { pump(); settle(); }) : () => {};

  const off = store.subscribe('', (path) => {
    if (path === '' || path === 'parts') { for (const p of partsByPriority()) schedule(p); return; }
    const k = path.split('.');
    if (k[0] !== 'parts') return;
    const part = Number(k[1]);
    if (!(part >= 0 && part < NUM_PARTS)) return;
    if (k.length === 2 || k[2] === 'userTerrain' || (k[2] === 'params' && (k.length === 3 || REGEN_KEYS.has(k[3])))) schedule(part);
  });

  // First fill: no debounce, selected part first.
  for (const p of partsByPriority()) refresh(p);

  return {
    /** Current full-resolution table of a slot ('A' | 'B' | 0 | 1), or null before it exists. */
    get(part, slot) {
      const s = slotIndex(slot);
      const p = Math.round(part);
      if (s < 0 || !(p >= 0 && p < NUM_PARTS)) return null;
      const lv = slots[p][s].levels;
      return lv ? { size: lv[0].size, data: lv[0].data } : null;
    },
    /** Resolves once every slot holds the table the store asks for. */
    whenIdle() {
      return new Promise((resolve) => { waiters.push(resolve); settle(); });
    },
    /** Re-post every current table (after the DSP node was rebuilt). */
    resendAll() {
      for (let p = 0; p < NUM_PARTS; p++) for (let s = 0; s < 2; s++) if (slots[p][s].levels) sendLevels(p, s, slots[p][s].levels);
    },
    /** Rebuild everything now (no debounce). */
    refreshAll() { for (const p of partsByPriority()) { clearTimeout(timers[p]); refresh(p); } },
    stats: () => ({ ...st, cached: cache.size, queued: queue.size, running: running.size }),
    dispose() {
      disposed = true;
      off();
      offFree();
      timers.forEach(t => clearTimeout(t));
      queue.clear();
      cache.clear();
      const w = waiters; waiters = [];
      for (const fn of w) fn();
    },
  };
}
