// 3D map harness: the real visuals with a real store and a fake engine.
// Query flags:
//   theme=light   start in the light theme
//   tele=0        no telemetry (audio not started yet)
//   play=0        no arpeggio
//   engine=none   no engine at all (terrains generated by the visuals)
//   view=top|low  start view;  quality=medium|low;  style=wire|contour|heat
//   mode=1|2      dot mode for part 1 (Roll / Drift)
//   lfo=1         modulate rotate and size with LFOs
//   panel=0       hide the control panel (clean screenshots)
//   part=N        select part N (0-3)
import '../../src/styles/theme.css';
import { createStore } from '../../src/core/store.js';
import { defaultState, PART_PARAM_MAP } from '../../src/core/params.js';
import { TERRAINS, PATHS } from '../../src/dsp/catalog.js';
import { createVisuals } from '../../src/visual/visuals.js';
import { createFakeEngine } from './fake-engine.js';

const q = new URLSearchParams(location.search);
const $ = (s) => document.querySelector(s);

async function boot() {
  const state = defaultState();
  // A livelier default than Init: rolling hills into mountains, a petalled orbit.
  Object.assign(state.parts[0].params, { morph: 0.3, pathShape: 2, pathOrder: 3, size: 0.24, centerX: 0.42, centerY: 0.56, spin: 0.06 });
  Object.assign(state.parts[1].params, { terrainA: 1, terrainB: 8, pathShape: 7, pathOrder: 3, size: 0.2, centerX: 0.6, centerY: 0.35 });
  Object.assign(state.parts[2].params, { terrainA: 9, terrainB: 12, pathShape: 4, pathOrder: 5, size: 0.18 });
  Object.assign(state.parts[3].params, { terrainA: 3, terrainB: 6, pathShape: 1, pathOrder: 2, size: 0.26 });
  const store = createStore(state);
  if (q.get('part')) store.set('ui.selectedPart', Number(q.get('part')));
  if (q.get('view')) store.set('ui.view', q.get('view'));
  if (q.get('quality')) store.set('ui.quality', q.get('quality'));
  if (q.get('style')) store.set('ui.renderStyle', q.get('style'));
  if (q.get('mode')) store.set('parts.0.dot.mode', Number(q.get('mode')));
  if (q.get('lfo') === '1') setLfo(store, true);

  const engine = q.get('engine') === 'none' ? null
    : createFakeEngine({ store, tele: q.get('tele') !== '0', play: q.get('play') !== '0' });
  const container = document.querySelector('[data-viewport]');
  const t0 = performance.now();
  const visuals = await createVisuals(container, { store, engine });
  const bootMs = performance.now() - t0;
  window.__vis = { store, engine, visuals, ready: true, bootMs };
  if (q.get('panel') === '0') $('#panel').classList.add('hidden');
  buildPanel(store, engine, visuals);
}

function setLfo(store, on) {
  const p = 'parts.0.mods.';
  store.set(p + 'rotate', { ...store.get(p + 'rotate'), lfoDepth: on ? 0.12 : 0, lfoRate: 0.15 });
  store.set(p + 'size', { ...store.get(p + 'size'), lfoDepth: on ? 0.12 : 0, lfoRate: 0.31 });
  store.set(p + 'morph', { ...store.get(p + 'morph'), lfoDepth: on ? 0.3 : 0, lfoRate: 0.07 });
}

function setTheme(theme) {
  document.documentElement.dataset.theme = theme;
  document.documentElement.style.colorScheme = theme;
  window.dispatchEvent(new CustomEvent('orograph:theme', { detail: { theme } }));
}
window.__setTheme = setTheme;

function buildPanel(store, engine, visuals) {
  const sel = () => store.get('ui.selectedPart');
  const path = (id) => `parts.${sel()}.params.${id}`;
  $('#theme').onclick = () => setTheme(document.documentElement.dataset.theme === 'light' ? 'dark' : 'light');
  for (const b of document.querySelectorAll('[data-view]')) b.onclick = () => visuals.setView(b.dataset.view);
  const opts = (el, list) => { el.innerHTML = list.map((n, i) => `<option value="${i}">${n}</option>`).join(''); };
  opts($('#palette'), visuals.palettes().map(p => p.name));
  opts($('#tA'), TERRAINS.map(t => t.name));
  opts($('#tB'), TERRAINS.map(t => t.name));
  opts($('#path'), PATHS.map(p => p.name));

  const sync = () => {
    $('#part').value = String(sel());
    $('#mode').value = String(store.get(`parts.${sel()}.dot.mode`));
    $('#quality').value = store.get('ui.quality');
    $('#style').value = store.get('ui.renderStyle');
    $('#palette').value = String(store.get('ui.palette'));
    $('#tA').value = String(store.get(path('terrainA')));
    $('#tB').value = String(store.get(path('terrainB')));
    $('#path').value = String(store.get(path('pathShape')));
    $('#order').value = String(store.get(path('pathOrder')));
    for (const inp of document.querySelectorAll('#sliders input')) inp.value = String(store.get(path(inp.dataset.id)));
  };
  $('#part').onchange = (e) => store.set('ui.selectedPart', Number(e.target.value));
  $('#mode').onchange = (e) => store.set(`parts.${sel()}.dot.mode`, Number(e.target.value), { source: 'ui' });
  $('#quality').onchange = (e) => store.set('ui.quality', e.target.value);
  $('#style').onchange = (e) => store.set('ui.renderStyle', e.target.value);
  $('#palette').onchange = (e) => store.set('ui.palette', Number(e.target.value));
  $('#tA').onchange = (e) => store.set(path('terrainA'), Number(e.target.value), { source: 'ui' });
  $('#tB').onchange = (e) => store.set(path('terrainB'), Number(e.target.value), { source: 'ui' });
  $('#path').onchange = (e) => store.set(path('pathShape'), Number(e.target.value), { source: 'ui' });
  $('#order').onchange = (e) => store.set(path('pathOrder'), Number(e.target.value), { source: 'ui' });

  const box = $('#sliders');
  for (const id of ['morph', 'warp', 'lift', 'fold', 'size', 'stretch', 'rotate', 'spin', 'pathParam', 'seed']) {
    const def = PART_PARAM_MAP[id];
    const row = document.createElement('div');
    row.className = 'row';
    row.innerHTML = `<label for="s-${id}">${def.label}</label><input id="s-${id}" data-id="${id}" type="range" min="${def.min}" max="${def.max}" step="${def.curve === 'int' ? 1 : (def.max - def.min) / 400}">`;
    box.appendChild(row);
    row.querySelector('input').oninput = (e) => store.set(path(id), Number(e.target.value), { source: 'ui' });
  }
  let lfo = false;
  $('#play').onclick = () => engine && engine.setPlaying(!engine.playing);
  $('#lfo').onclick = () => { lfo = !lfo; setLfo(store, lfo); };
  $('#rot').onclick = () => visuals.toggleAutoRotate();
  store.subscribe('', () => sync());
  sync();
  setInterval(() => {
    const s = visuals.debug.stats();
    const d = visuals.debug.dot();
    $('#stats').textContent = `fps ${s.fps.toFixed(1)}  cpu ${s.cpuMsPerFrame.toFixed(2)} ms\ncalls ${s.drawCalls}  tris ${(s.triangles / 1000).toFixed(0)}k\ndot ${d.u.toFixed(3)}, ${d.v.toFixed(3)}  ${s.physics[sel()]}`;
  }, 500);
}

boot().catch((err) => {
  console.error('[visual harness] failed', err);
  const pre = document.createElement('pre');
  pre.style.cssText = 'position:fixed;inset:0;margin:0;padding:20px;color:#f88;background:#111;white-space:pre-wrap;z-index:99';
  pre.textContent = String(err && err.stack || err);
  document.body.appendChild(pre);
});
